name: Setup conan
description: Setup conan

runs:
  using: 'composite'
  steps:
    - name: Install conan
      if: env.os != 'macos-14'
      uses: turtlebrowser/get-conan@main
      with:
        version: 2.1.0

    - name: Config profile
      run: |
        conan profile detect --force
        if [ "$RUNNER_OS" == "Linux" ]; then
          echo "
            [settings]
            arch=x86_64
            build_type=${{ env.conanBuildType }}
            compiler=clang
            compiler.cppstd=gnu23
            compiler.libcxx=libc++
            compiler.version=14
            os=Linux
            [conf]
            tools.system.package_manager:mode=install
            tools.system.package_manager:sudo=True
            tools.cmake.cmaketoolchain:generator=Unix Makefiles
          " > /home/runner/.conan2/profiles/default
        elif [ "$RUNNER_OS" == "Windows" ]; then
          echo "
            [settings]
            os=Windows
            arch=x86_64
            compiler=msvc
            compiler.version=193
            compiler.runtime=dynamic
            build_type=${{ env.conanBuildType }}
            [tool_requires]
            emsdk/3.1.44
            [conf]
            tools.system.package_manager:mode=install
          " > C:\\Users\\runneradmin\\.conan2\\profiles\\default
        elif [ "$RUNNER_OS" == "macOS" ]; then
          echo "
            [settings]
            arch=armv8
            build_type=${{ env.conanBuildType }}
            compiler=apple-clang
            compiler.cppstd=gnu23
            compiler.libcxx=libc++
            compiler.version=15
            os=Macos
            [conf]
            tools.system.package_manager:mode=install
            tools.system.package_manager:sudo=True
            tools.cmake.cmaketoolchain:generator=Unix Makefiles
          " > /Users/runner/.conan2/profiles/default
        else
          echo "$RUNNER_OS not supported"
          exit 1
        fi
      shell: bash

    - name: Config wasm profile
      if: env.wasm == 'true'
      run: |
        conan profile detect --force --name wasm
        if [ "$RUNNER_OS" == "Linux" ]; then
          echo "
            [settings]
            arch=wasm
            compiler=clang
            build_type=${{ env.conanBuildType }}
            compiler.cppstd=gnu23
            compiler.libcxx=libc++
            compiler.version=15
            os=Emscripten
            [tool_requires]
            emsdk/3.1.44
            [conf]
            tools.system.package_manager:mode=install
            tools.system.package_manager:sudo=True
            tools.cmake.cmaketoolchain:generator=Unix Makefiles
          " > /home/runner/.conan2/profiles/wasm
        elif [ "$RUNNER_OS" == "Windows" ]; then
          echo "
            [settings]
            arch=wasm
            build_type=${{ env.conanBuildType }}
            compiler=msvc
            compiler.version=193
            compiler.runtime=dynamic
            os=Emscripten
            [tool_requires]
            emsdk/3.1.44
            [conf]
            tools.system.package_manager:mode=install
          " > C:\\Users\\runneradmin\\.conan2\\profiles\\wasm
        elif [ "$RUNNER_OS" == "macOS" ]; then
          echo "
            [settings]
            arch=wasm
            compiler=clang
            build_type=${{ env.conanBuildType }}
            compiler.cppstd=gnu23
            compiler.libcxx=libc++
            compiler.version=15
            os=Emscripten
            [tool_requires]
            emsdk/3.1.44
            [conf]
            tools.system.package_manager:mode=install
            tools.system.package_manager:sudo=True
            tools.cmake.cmaketoolchain:generator=Unix Makefiles
          " > /Users/runner/.conan2/profiles/wasm
        else
          echo "$RUNNER_OS not supported"
          exit 1
        fi
      shell: bash

    - name: Setup conan cache
      uses: ./.github/workflows/utils/cache/get-conan-cache

    - name: Install dependencies
      if: env.wasm == 'false'
      shell: bash
      run: |
        wm run conan-install -bt ${{ env.conanBuildType }}

    - name: Install dependencies
      if: env.wasm == 'true'
      shell: bash
      run: |
        wm run conan-install -bt ${{ env.conanBuildType }} -w
