name: Lint native
description: Lint native

runs:
  using: 'composite'
  steps:
    - name: Lint
      uses: DoozyX/clang-format-lint-action@v0.17
      with:
        source: './Renderer'
        extensions: 'h,cpp'
        clangFormatVersion: 17
        inplace: true
