name: Install dependencies renderer
description: Install dependencies renderer

runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        export CC=${{ env.cc }}
        export CXX=${{ env.cxx }}
        wm run conan-install -bt ${{ env.engineBuildType }}
