name: Lint logger
description: Lint logger

runs:
  using: 'composite'
  steps:
    - name: Lint
      uses: DoozyX/clang-format-lint-action@v0.17
      with:
        source: './Logger'
        exclude: './game/data'
        extensions: 'h,cpp'
        clangFormatVersion: 17
        inplace: true
